- name: docker build and push
  hosts: local  # Replace with the hostname or IP address of your target server
  tasks:
    - name: Update apt package cache
      become: yes
      apt:
        update_cache: yes

    - name: Build Docker Image
      become: yes
      command: docker build -t petstore2 .
      args:
        chdir: /var/lib/jenkins/workspace/petstore

    - name: Tag image
      become: yes
      command: docker tag petstore2:latest onusharma/petstore2:latest

   

    - name: Push image
      become: yes
      command: docker push onusharma/petstore2:latest

    - name: Run container
      become: yes
      command: docker run -d --name pet1 -p 8081:8080 onusharma/petstore2:latest
