- name: docker build and push
  hosts: local  # Replace with the hostname or IP address of your target server
  tasks:
    - name: Update apt package cache
      become: yes
      apt:
        update_cache: yes

    - name: Build Docker Image
      become: yes
      command: docker build -t petstore .
      args:
        chdir: /var/lib/jenkins/workspace/petstore

    - name: Tag image
      become: yes
      command: docker tag petstore:latest onusharma/petstore:latest

    - name: Log in to Docker Hub
      become: yes
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: onusharma
        password: dckr_pat_ckWCTO2Q9i6TllpeEVjWFl0MlOM/PAT

    - name: Push image
      become: yes
      command: docker push onusharma/petstore:latest

    - name: Run container
      become: yes
      command: docker run -d --name pet1 -p 8081:8080 onusharma/petstore:latest
